// <auto-generated />
using System;
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20220326141957_SeedProductTable")]
    partial class SeedProductTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b37575e-68f4-4ca7-b490-979f6f829fd4"),
                            CategoryName = "T-shirt",
                            Description = "Camisa social P",
                            ImageURL = "https://th.bing.com/th/id/R.2a89878829d77f092f240129da8b185b?rik=3eK%2b3Ekb18pHjA&pid=ImgRaw&r=0",
                            Name = "Camisa Social",
                            Price = 69.90m
                        },
                        new
                        {
                            Id = new Guid("aad1b00c-c23e-40fe-aecd-e0244cfd24a4"),
                            CategoryName = "T-shirt",
                            Description = "Camisa do vasco",
                            ImageURL = "https://th.bing.com/th/id/R.222559365766c1c20d5a484703a08de1?rik=NAt9lgVgbDm1UQ&pid=ImgRaw&r=0",
                            Name = "Camisa Time",
                            Price = 150.90m
                        },
                        new
                        {
                            Id = new Guid("877a28c3-f665-4648-b9cb-fd8107054ce4"),
                            CategoryName = "T-shirt",
                            Description = "Camisa adidas M",
                            ImageURL = "https://th.bing.com/th/id/OIP.8gSxyAC3iGCbLdA726Y2TAHaHa?pid=ImgDet&rs=1",
                            Name = "Camisa Adidas",
                            Price = 35.90m
                        },
                        new
                        {
                            Id = new Guid("5aebe930-e94a-4190-a064-cf12ce470f26"),
                            CategoryName = "T-shirt",
                            Description = "Camisa feminina manga longa",
                            ImageURL = "https://th.bing.com/th/id/R.1db75a836a6023f811d21452a8cb93db?rik=SJW8sBtMBBREeg&riu=http%3a%2f%2fmaxdicas.com%2fwp-content%2fuploads%2f2016%2f07%2fcamisa-feminina-xadrez-da-moda.jpg&ehk=yz1Tn4oClJNlMtbf3YkrplbHFJTDhfoLgP9iwXo4m84%3d&risl=&pid=ImgRaw&r=0",
                            Name = "Camisa Social Feminina",
                            Price = 80.90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
