// <auto-generated />
using System;
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20220415135226_AddTableProduct")]
    partial class AddTableProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7ea6905-ca4a-4aa6-a03f-b65873aed73c"),
                            CategoryName = "T-shirt",
                            Description = "Camisa social P",
                            ImageURL = "2_no_internet.jpg",
                            Name = "Camisa Jurassic Park",
                            Price = 69.90m
                        },
                        new
                        {
                            Id = new Guid("18661af9-5265-44dc-9494-25af9f860f78"),
                            CategoryName = "T-shirt",
                            Description = "Camisa do star wars",
                            ImageURL = "4_storm_tropper.jpg",
                            Name = "Camisa Star Wars",
                            Price = 150.90m
                        },
                        new
                        {
                            Id = new Guid("37da0635-2b87-4909-8744-faccb6ae015b"),
                            CategoryName = "T-shirt",
                            Description = "Camisa spaceX M",
                            ImageURL = "6_spacex.jpg",
                            Name = "Camisa SpaceX",
                            Price = 35.90m
                        },
                        new
                        {
                            Id = new Guid("34154b02-b59c-4004-973d-b900e453e70f"),
                            CategoryName = "Caneca",
                            Description = "Linda caneca do mario",
                            ImageURL = "1_super_mario.jpg",
                            Name = "Caneca Mario",
                            Price = 15.90m
                        },
                        new
                        {
                            Id = new Guid("d460cf81-cb95-4726-ad5d-4152e587e7c2"),
                            CategoryName = "Brinquedo",
                            Description = "Nave millenium falcon do star wars",
                            ImageURL = "10_milennium_falcon.jpg",
                            Name = "Nave Millenium Falcon",
                            Price = 1500m
                        },
                        new
                        {
                            Id = new Guid("b1d7752e-07ad-45df-9d88-072a04c0be6c"),
                            CategoryName = "T-shirt",
                            Description = "Camisa do dragon ball G",
                            ImageURL = "13_dragon_ball.jpg",
                            Name = "Camisa Dragon Ball",
                            Price = 55.90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
